# config file for [air](https://github.com/cosmtrek/air) in toml format

# working directory (. or absolute path)
# other configured directory paths must be under root
root = "."
tmp_dir = "out/tmp"

[build]
# binary file path yielded from `cmd`
bin = "out/tmp/domain"

# plain shell command
cmd = "go build -mod readonly -o out/tmp/domain ./cmd/httpserver"

# rebuild delay (ms)
delay = 1000

# customize binary
# this is how you start to run your application
# application works like a cli
# full_bin = "./tmp/app/engine http"

# ignore directories with these names
# ignore files with these name or extensions
exclude_dir = ["out", "vendor"]

# watch files with these extensions
include_ext = ["go", "yaml", "toml"]

# log file is placed in `tmp_dir`
log = "air_errors.log"

[log]
# show log time
time = true

[misc]
# delete tmp directory on exit
clean_on_exit = true
