# default configuration

[external.services.example]
baseURL = "http://www.google.com"
timeout = 25000

[http.router]
namespace = "domain"

[http.router.paging]
defaultLimit = 20
defaultOffset = 0

[http.router.sorting]
defaultAttr = "created_on"
defaultOrder = "desc"

[http.server]
host = "0.0.0.0"
mode = "debug"
port = 9202

[logger.app]
enabled = true
level = "info"

[logger.domain]
enabled = false
level = "info"

[logger.http]
enabled = true
level = "info"

[logger.repos]
enabled = true
level = "info"

[metadata]
path = "/app/package.json"

[postgres]
database = "svcdb"
host = "localhost"
password = "postgres"
port = 5432
user = "postgres"
