# default configuration

[external.services.example]
baseURL = "http://www.google.com"
timeout = 25000

[http.router]
namespace = "domain"

[http.router.paging]
defaultLimit = 20
defaultOffset = 0

[http.router.sorting]
defaultAttr = "created_on"
defaultOrder = "desc"

[http.server]
host = "0.0.0.0"
mode = "debug"
port = 9202

[logger]
enabled = true
level = "info"
verbose = true

[metadata]
environment = "development"

[postgres]
database = "svcdb"
host = "localhost"
password = "postgres"
port = 5432
user = "postgres"
