# configuration file
# config defined here can be used to update runtime configuration without the need for app restart
# NOTE: for a given config key, if a bound environment variable exists, changes here will have no effect on its value

[logger]
format = "json"
level = "info"
verbose = true
